/***********************************************************************/
/*                                                                     */
/*  FILE        :LCD02.c                                               */
/*  DATE        :Fri, Oct 20, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h";
#include "lcd_func.h";

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void displaySwitchStatus(int s1,int s2,int s3,int s4){
	if(s1==0){
		lcd_xy(5,1);
		lcd_puts("OFF");
	}else if(s1==1){
		lcd_xy(5,1);
		lcd_puts("ON ");
	}
	
	if(s2==0){
		lcd_xy(13,1);
		lcd_puts("OFF");
	}else if(s2==1){
		lcd_xy(13,1);
		lcd_puts("ON ");
	}
	
	if(s3==0){
		lcd_xy(5,2);
		lcd_puts("OFF");
	}else if(s3==1){
		lcd_xy(5,2);
		lcd_puts("ON ");
	}
	
	if(s4==0){
		lcd_xy(13,2);
		lcd_puts("OFF");
	}else if(s4==1){
		lcd_xy(13,2);
		lcd_puts("ON ");
	}
}
void main(void)
{
	int sw[4];
	
	lcd_init();
	lcd_xy(1,1);
	lcd_puts("SW1=OFF");
	
	lcd_xy(9,1);
	lcd_puts("SW2=OFF");
	
	lcd_xy(1,2);
	lcd_puts("SW3=OFF");
	
	lcd_xy(9,2);
	lcd_puts("SW4=OFF");
	
	for(;;){
		if(IO.PDR1.BIT.B4 == 0){
			sw[0]=1;
		}
		if(IO.PDR1.BIT.B5 == 0){
			sw[1]=1;
		}
		if(IO.PDR1.BIT.B6 == 0){
			sw[2]=1;
		}
		if(IO.PDR1.BIT.B7 == 0){
			sw[3]=1;
		}
		
		if(IO.PDR1.BIT.B4 == 1){
			sw[0]=0;
		}
		if(IO.PDR1.BIT.B5 == 1){
			sw[1]=0;
		}
		if(IO.PDR1.BIT.B6 == 1){
			sw[2]=0;
		}
		if(IO.PDR1.BIT.B7 == 1){
			sw[3]=0;
		}
		
		displaySwitchStatus(sw[0],sw[1],sw[2],sw[3]);
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
