/***********************************************************************/
/*                                                                     */
/*  FILE        :THERMO.c                                              */
/*  DATE        :Thu, Nov 16, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h";
#include "lcd_func.h";

#define AVERAGE_NUM 100

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	float ad_data;
	float temp;
	int count=0;

	AD.ADCSR.BYTE=0x04;
	
	lcd_init();

	lcd_xy(4,1);
	lcd_puts("C");
	for(;;){
		if(count>=AVERAGE_NUM){
			count=0;
			lcd_xy(1,1);
			lcd_dataout(temp/AVERAGE_NUM);
			temp=0;
		}
		
		AD.ADCSR.BIT.ADST=1;
		
		for(;AD.ADCSR.BIT.ADF!=1;){}
		AD.ADCSR.BIT.ADF=0;
		
		ad_data=AD.ADDRA>>6;//data read before AD transform
		temp+=((ad_data/1023)*5.0)*100-50;
		//(ad_data/1023)*5.0	get voltage value (0-5)
		//valtage *100-50		voltage * 100 - 50 = temp
		
		count++;
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
