/***********************************************************************/
/*                                                                     */
/*  FILE        :LED02.c                                               */
/*  DATE        :Fri, Oct 06, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	IO.PCR3 = 0xFF;
	IO.PDR3.BYTE = 0xAA;
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
