/***********************************************************************/
/*                                                                     */
/*  FILE        :SERVO01.c                                             */
/*  DATE        :Fri, Jan 19, 2018                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

//used P62 port.
       
#include "iodefine.h"
#include <machine.h>

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void onSwitchPushed(int no){
	switch(no){
		case 1:
			TZ0.GRC=3000;
			IRR1.BIT.IRRI0=0;
			break;
		case 3:
			TZ0.GRC=2200;
			IRR1.BIT.IRRI2=0;
			break;
		case 4:
			TZ0.GRC=3800;
			IRR1.BIT.IRRI3=0;
			break;
	}
	
	TZ.TOER.BIT.EC0=0;
	TZ0.TCNT=0;
	TZ.TSTR.BIT.STR0=1;
}
void main(void)
{
	set_imask_ccr(1);
	IO.PMR1.BYTE=0xF0;
	IEGR1.BYTE=0x00;
	IENR1.BYTE=0x1F;
	IRR1.BYTE=0x30;
	
	TZ0.TCR.BYTE=0x23;
	TZ0.POCR.BYTE=0xF8;
	TZ.TPMR.BYTE=0x8E;
	TZ.TOCR.BYTE=0x0C;
	TZ0.GRA=20000;
	TZ0.GRC=0;
	TZ0.GRD=0;
	set_imask_ccr(0);
	
	TZ.TOER.BIT.EC0=1;
	//TZ.TOER.BIT.ED0=1;
	TZ.TSTR.BIT.STR0=0;
	TZ0.GRC=0;
	TZ0.GRD=0;
	
	while(1);
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
