/***********************************************************************/
/*                                                                     */
/*  FILE        :SerialR.c                                             */
/*  DATE        :Fri, Jan 26, 2018                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h";
#include "lcd_func.h";
#include <machine.h>

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

float temp=0;
unsigned char rcv_data;

void displayTempData(){	
	if(SCI3_2.SSR.BIT.RDRF==1){
		rcv_data=SCI3_2.RDR;
		if(rcv_data!=temp){
			lcd_clear();
			lcd_xy(1,1);
			lcd_dataout(rcv_data);
			temp=rcv_data;
		}
		SCI3_2.SSR.BIT.RDRF=0;
	}else{
		SCI3_2.SSR.BIT.OER=0;
		SCI3_2.SSR.BIT.FER=0;
		SCI3_2.SSR.BIT.PER=0;
	}
}

void wait(){
	int i;
	for(i=0;i<10000;i++){
		
	}
}

void main(void){
	lcd_init();
	
	SCI3_2.SCR3.BIT.RE=0;
	SCI3_2.SMR.BYTE=0x00;
	SCI3_2.BRR=64;
	
	SCI3_2.SSR.BIT.OER=0;
	SCI3_2.SSR.BIT.FER=0;
	SCI3_2.SSR.BIT.PER=0;
	
	wait();
	
	SCI3_2.SCR3.BIT.RE=1;
	SCI3_2.SCR3.BIT.RIE=1;

	for(;;){}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
