/***********************************************************************/
/*                                                                     */
/*  FILE        :7SEG01.c                                              */
/*  DATE        :Fri, Oct 20, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h";

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{	
	int count=0;
	int i,j;
	int isPush=0;
	int segnums[]={0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09};
	
	IO.PCR2 = 0xFF;
	IO.PCR3 = 0xFF;
	IO.PCR5 = 0xFF;
	
	for(;;){
		if(isPush==0){
			if(IO.PDR1.BIT.B4 == 0){//count up
				isPush=1;
				count+=1;
				if(count>9||count<0){
					count=0;
				}
			}else if(IO.PDR1.BIT.B5 == 0){//count down
				isPush=1;
				count-=1;
				if(count>9||count<0){
					count=0;
				}
			}else if(IO.PDR1.BIT.B7 == 0){//reset
				isPush=1;
				count=0;
				if(count>9||count<0){
					count=0;
				}
			}
		}else{
			if(IO.PDR1.BIT.B4 == 1 && IO.PDR1.BIT.B5 == 1 && IO.PDR1.BIT.B7 == 1){
				isPush=0;
			}
		}
		
		for(i=0;i<100;i++){
			for(j=0;j<10;j++){
			}
		}
		
		IO.PDR5.BYTE=segnums[count];
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
