/***********************************************************************/
/*                                                                     */
/*  FILE        :SW02.c                                                */
/*  DATE        :Fri, Nov 17, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h";
#include <machine.h>

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void SW1(){
	IO.PDR2.BIT.B0=1;
	IRR1.BIT.IRRI0=0;
}

void SW2(){
	IO.PDR2.BIT.B0=0;
	IRR1.BIT.IRRI1=0;
}
void main(void)
{
	IO.PCR2 = 0xFF;
	
	set_imask_ccr(1);
	
	IO.PMR1.BYTE=0x30;
	IEGR1.BYTE=0x00;
	IENR1.BYTE=0x03;
	IRR1.BYTE=0x30;
	
	set_imask_ccr(0);
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
