c/***********************************************************************/
/*                                                                     */
/*  FILE        :AD01.c                                                */
/*  DATE        :Fri, Oct 27, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h";

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	unsigned int ad_data=0;
	
	IO.PCR3=0xFF;
	
	AD.ADCSR.BYTE=0x05;
	
	for(;;){
		AD.ADCSR.BIT.ADST=1;
		
		for(;AD.ADCSR.BIT.ADF!=1;){}
		
		ad_data=AD.ADDRB>>6;
		AD.ADCSR.BIT.ADF=0;
		IO.PDR3.BYTE=ad_data>>2;
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
