/***********************************************************************/
/*                                                                     */
/*  FILE        :LED03.c                                               */
/*  DATE        :Fri, Oct 13, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif
void wait(unsigned int count){
	int i;
	for(i=0;i<count*10000;i++){
		
	}
}
void main(void)
{
	unsigned int ledno=1;
	int i;
	IO.PCR3 = 0xFF;
	for(i=0;;i++){		
		IO.PDR3.BYTE = ledno;
		
		ledno=ledno*2;
		
		if(ledno>128){
			ledno=1;
		}
		
		wait(1000);
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
