/***********************************************************************/
/*                                                                     */
/*  FILE        :AD02.c                                                */
/*  DATE        :Fri, Oct 27, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h";
#include "lcd_func.h";

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void displayLevel(int vr1,int vr2){
	lcd_xy(5,1);
	lcd_puts("   ");
	lcd_xy(5,2);
	lcd_puts("   ");
	if(vr1<10){
		lcd_xy(7,1);
		lcd_dataout(vr1);
	}else if(vr1<100){
		lcd_xy(6,1);
		lcd_dataout(vr1);
	}else{
		lcd_xy(5,1);
		lcd_dataout(vr1);
	}
	
	if(vr2<10){
		lcd_xy(7,2);
		lcd_dataout(vr2);
	}else if(vr2<100){
		lcd_xy(6,2);
		lcd_dataout(vr2);
	}else{
		lcd_xy(5,2);
		lcd_dataout(vr2);
	}
}
void main(void)
{
	unsigned int ad_data1=0;
	unsigned int ad_data2=0;
		
	AD.ADCSR.BYTE=0x16;
	
	lcd_init();
	
	for(;;){
		lcd_xy(1,1);
		lcd_puts("VR1:");
		lcd_xy(8,1);
		lcd_puts("[%]");
		lcd_xy(1,2);
		lcd_puts("VR2:");
		lcd_xy(8,2);
		lcd_puts("[%]");
		
		AD.ADCSR.BIT.ADST=1;
		
		for(;AD.ADCSR.BIT.ADF!=1;){}
		
		ad_data1=AD.ADDRB>>6;
		ad_data1=(int)((double)ad_data1*100.0/1023.00);
		ad_data2=AD.ADDRC>>6;
		ad_data2=(int)((double)ad_data2*100.0/1023.00);
		displayLevel(ad_data1,ad_data2);
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
