/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.h                                                */
/*  DATE        :Fri, Jan 12, 2018                                     */
/*  DESCRIPTION :Header file of sbrk file                              */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
/* size of area managed by sbrk */
#define HEAPSIZE 0x200
