/***********************************************************************/
/*                                                                     */
/*  FILE        :TB01.c                                                */
/*  DATE        :Fri, Nov 24, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h";
#include <machine.h>

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void TIMER_B1(){
	static int count=0;
	
	count++;
	
	if(count==114){
		IO.PDR2.BIT.B0=1;
	}else if(count==152){
		IO.PDR2.BIT.B0=0;
		count=0;
	}
	
	IRR2.BIT.IRRTB1=0;
}

void main(void)
{
	IO.PCR2=0x01;
	IO.PCR3=0xFF;
	
	set_imask_ccr(1);
	
	TB1.TMB1.BIT.RLD=0;
	TB1.TMB1.BIT.CKS=1;
	IRR2.BIT.IRRTB1=0;
	IENR2.BIT.IENTB1=1;
	TB1.TLB1=0;
	
	set_imask_ccr(0);
	
	while(1);
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
