/***********************************************************************/
/*                                                                     */
/*  FILE        :SW01.c                                                */
/*  DATE        :Fri, Oct 13, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	IO.PCR2 = 0xFF;
	IO.PCR3 = 0xFF;
	
	for(;;){
		if(IO.PDR1.BIT.B4 == 0){
			IO.PDR3.BYTE = 0x02;
		}else if(IO.PDR1.BIT.B5 == 0){
			IO.PDR3.BYTE = 0x04;
		}else if(IO.PDR1.BIT.B7 == 0){
			IO.PDR2.BYTE = 0x01;
		}else{
			IO.PDR3.BYTE = 0x00;
			IO.PDR2.BYTE = 0x00;
		}
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
