/***********************************************************************/
/*                                                                     */
/*  FILE        :SerialT.c                                             */
/*  DATE        :Fri, Jan 26, 2018                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h";
#include "lcd_func.h";

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void wait(){
	int i;
	for(i=0;i<10000;i++){
		
	}
}

void main(void){
	float ad_data;
	float temp=0;
	
	lcd_init();
	
	IO.PMR1.BYTE=0x08;
	
	SCI3.SCR3.BIT.TE=0;
	SCI3.SMR.BYTE=0x00;
	SCI3.BRR=64;
	SCI3.TDR=0x00;
	
	SCI3_2.SCR3.BIT.TE=0;
	SCI3_2.SMR.BYTE=0x00;
	SCI3_2.BRR=64;
	SCI3_2.TDR=0x00;
	
	wait();
	
	SCI3.SCR3.BIT.TE=1;
	SCI3_2.SCR3.BIT.TE=1;
	
	AD.ADCSR.BYTE=0x04;
	
	for(;;){
		AD.ADCSR.BIT.ADST=1;
		
		for(;AD.ADCSR.BIT.ADF!=1;){}
		AD.ADCSR.BIT.ADF=0;
		
		ad_data=AD.ADDRA>>6;
		temp=((ad_data/1023)*5.0)*100-50;
		
		wait();
		
		lcd_xy(1,1);
		lcd_dataout(temp);
		
		if(SCI3.SSR.BIT.TDRE==1){
			SCI3.TDR=temp;
		}
		if(SCI3_2.SSR.BIT.TDRE==1){
			SCI3_2.TDR=temp;
		}
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
