/***********************************************************************/
/*                                                                     */
/*  FILE        :TIMER.c                                               */
/*  DATE        :Fri, Nov 24, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h";
#include <machine.h>

int countNum=0;
int isTimerStarted=0;

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void timerSet(int min){
	countNum=min*60*38;
	IO.PCR3 = 0xFF;
	switch(min){
		case 1:
			IO.PDR3.BYTE = 0x03;
			IRR1.BIT.IRRI0=0;
			IO.PDR5.BYTE=0x01;
			break;
		case 2:
			IO.PDR3.BYTE = 0x0F;
			IRR1.BIT.IRRI1=0;
			IO.PDR5.BYTE=0x02;
			break;
		case 3:
			IO.PDR3.BYTE = 0x3F;
			IRR1.BIT.IRRI2=0;
			IO.PDR5.BYTE=0x03;
			break;
		default:
			IO.PDR3.BYTE = 0x00;
			break;
	}
}
void timerStart(){
	isTimerStarted=1;
	IRR1.BIT.IRRI3=0;
}
void countPerSec(){
	static int count=0;
	static int isLedOn=0;
	static int isCountFinished=0;
	if(!isTimerStarted){
		return;
	}
	
	if(count==countNum){//count finish
		isCountFinished=1;
		IO.PDR3.BYTE = 0x00;
		IO.PDR5.BYTE=0x00;
	}
	if(isCountFinished){
		if((count-countNum)<10*38){
			if(count%16==0){
				IO.PDR2.BIT.B0=0;
			}else{
				IO.PDR2.BIT.B0=1;
			}
		}else if((count-countNum)<20*38){
			if(count%8==0){
				IO.PDR2.BIT.B0=0;
			}else{
				IO.PDR2.BIT.B0=1;
			}
		}else if((count-countNum)<30*38){
			if(count%4==0){
				IO.PDR2.BIT.B0=0;
			}else{
				IO.PDR2.BIT.B0=1;
			}
		}else{
			IO.PDR2.BIT.B0=0;
			isTimerStarted=0;
		}
	}
	
	switch(((countNum-count)/38)+1){
		case 30:
			IO.PDR3.BYTE = 0x01;
			break;
		case 60:
			IO.PDR3.BYTE = 0x03;
			IO.PDR5.BYTE=0x01;
			break;
		case 90:
			IO.PDR3.BYTE = 0x07;
			break;
		case 120:
			IO.PDR3.BYTE = 0x0F;
			IO.PDR5.BYTE=0x02;
			break;
		case 150:
			IO.PDR3.BYTE = 0x1F;
			break;
		case 180:
			IO.PDR3.BYTE = 0x3F;
			IO.PDR5.BYTE=0x03;
			break;
	}
	
	if((count%38)==0){
		if(isLedOn){
			IO.PDR3.BIT.B7 = 0;
			isLedOn=0;
		}else{
			IO.PDR3.BIT.B7 = 1;
			isLedOn=1;
		}
	}
	
	count++;
	
	IRR2.BIT.IRRTB1=0;
}
void main(void)
{
	IO.PCR2=0x01;
	IO.PCR5 = 0xFF;
	set_imask_ccr(1);
	
	TB1.TMB1.BIT.RLD=0;
	TB1.TMB1.BIT.CKS=1;
	IRR2.BIT.IRRTB1=0;
	IENR2.BIT.IENTB1=1;
	TB1.TLB1=0;
	
	IO.PMR1.BYTE=0xF0;
	IEGR1.BYTE=0x00;
	IENR1.BYTE=0x0F;
	IRR1.BYTE=0x30;
	
	set_imask_ccr(0);
	
	while(1);
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
