/***********************************************************************/
/*                                                                     */
/*  FILE        :serial02T.c                                           */
/*  DATE        :Fri, Dec 22, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h";
#include <machine.h>

int flag=0;

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void IRQ_SW1(){
	IO.PDR3.BIT.B0=~IO.PDR3.BIT.B0;
	IRR1.BIT.IRRI0=0;
	flag=1;
}
void IRQ_SW2(){
	IO.PDR3.BIT.B1=~IO.PDR3.BIT.B1;
	IRR1.BIT.IRRI1=0;
	flag=2;
}
void wait(){
	int i;
	for(i=0;i<10000;i++){
		
	}
}

void main(void){
	IO.PCR3=0xFF;
	IO.PMR1.BYTE=0x38;
	IEGR1.BYTE=0x70;
	IENR1.BYTE=0x13;
	IRR1.BYTE=0x30;
	
	SCI3_2.SCR3.BIT.TE=0;
	SCI3_2.SMR.BYTE=0x00;
	SCI3_2.BRR=64;
	SCI3_2.TDR=0x00;
	
	wait();
	
	SCI3_2.SCR3.BIT.TE=1;
	
	while(1){
		if(flag!=0&&SCI3_2.SSR.BIT.TDRE==1){
			switch(flag){
				case 1:SCI3_2.TDR=0x01;break;
				case 2:SCI3_2.TDR=0x02;break;
			}
			
			flag=0;
		}
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
